[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
txodds_prediction_market = "2AEnPyT7dpi9jiDKjj767TGZdHZq7iUemmzDoL27Vjtx"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
